version: '3.7'

services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - 8880:1337  
    volumes:
      - ./:/app 
      - logs:/app/logs  
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  logs:
    driver: local

